// Seed data shown when no Supabase DB is connected.
export const DUMMY_STARTUPS = [
  {
    id: "00000001-0000-0000-0000-000000000001",
    startup_name: "Bazaar Technologies",
    tagline: "Digitising Pakistan's retail supply chain for kiryana stores",
    primary_industry: "E-Commerce",
    nic_name: "LUMS CE",
    city: "Karachi",
    website: "https://bazaar.pk",
    logo_url: "https://logo.clearbit.com/bazaartech.com",
    founder_name: "Hamza Jawaid",
    founder_role: "Co-founder & Co-CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/men/32.jpg",
    current_revenue: 120_000_000,
    investment_raised: 30_000_000,
    number_of_customers: 85000,
    total_employees: 420,
    pasha_verified: true,
  },
  {
    id: "00000002-0000-0000-0000-000000000002",
    startup_name: "Airlift Technologies",
    tagline: "On-demand mass transit and last-mile logistics",
    primary_industry: "Transport & Logistics",
    nic_name: "NIC Lahore",
    city: "Lahore",
    website: "https://airlift.pk",
    logo_url: "https://logo.clearbit.com/airlift.com",
    founder_name: "Usman Gul",
    founder_role: "Founder & CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/men/45.jpg",
    current_revenue: 80_000_000,
    investment_raised: 85_000_000,
    number_of_customers: 200000,
    total_employees: 550,
    pasha_verified: true,
  },
  {
    id: "00000003-0000-0000-0000-000000000003",
    startup_name: "Meezan FinTech",
    tagline: "Shariah-compliant digital banking for the unbanked",
    primary_industry: "FinTech",
    nic_name: "IBA Karachi",
    city: "Karachi",
    website: "https://meezanfintech.pk",
    logo_url: "https://logo.clearbit.com/meezanbank.com",
    founder_name: "Ayesha Khan",
    founder_role: "Founder & CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/women/44.jpg",
    current_revenue: 45_000_000,
    investment_raised: 12_000_000,
    number_of_customers: 310000,
    total_employees: 180,
    pasha_verified: false,
  },
  {
    id: "00000004-0000-0000-0000-000000000004",
    startup_name: "Sabzbari",
    tagline: "Farm-to-table fresh produce delivery in 90 minutes",
    primary_industry: "AgriTech",
    nic_name: "NUST NIC",
    city: "Islamabad",
    website: "https://sabzbari.pk",
    logo_url: "https://logo.clearbit.com/freshdirect.com",
    founder_name: "Bilal Ahmed",
    founder_role: "Co-founder",
    founder_photo_url: "https://randomuser.me/api/portraits/men/52.jpg",
    current_revenue: 18_000_000,
    investment_raised: 5_000_000,
    number_of_customers: 22000,
    total_employees: 95,
    pasha_verified: false,
  },
  {
    id: "00000005-0000-0000-0000-000000000005",
    startup_name: "Sehat Kahani",
    tagline: "Connecting patients to female doctors via telemedicine",
    primary_industry: "HealthTech",
    nic_name: "Plan9",
    city: "Karachi",
    website: "https://sehatkahani.com",
    logo_url: "https://logo.clearbit.com/sehatkahani.com",
    founder_name: "Dr. Sara Saeed",
    founder_role: "Co-founder & CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/women/68.jpg",
    current_revenue: 28_000_000,
    investment_raised: 7_500_000,
    number_of_customers: 60000,
    total_employees: 130,
    pasha_verified: true,
  },
  {
    id: "00000006-0000-0000-0000-000000000006",
    startup_name: "TalentX",
    tagline: "AI-powered hiring platform for Pakistan's tech talent",
    primary_industry: "HR Tech",
    nic_name: "NIC Lahore",
    city: "Lahore",
    website: "https://talentx.pk",
    logo_url: "https://logo.clearbit.com/lever.co",
    founder_name: "Zainab Iqbal",
    founder_role: "Founder",
    founder_photo_url: "https://randomuser.me/api/portraits/women/22.jpg",
    current_revenue: 9_000_000,
    investment_raised: 2_000_000,
    number_of_customers: 1200,
    total_employees: 48,
    pasha_verified: false,
  },
  {
    id: "00000007-0000-0000-0000-000000000007",
    startup_name: "CreditBook",
    tagline: "Digital ledger & credit scoring for small businesses",
    primary_industry: "FinTech",
    nic_name: "LUMS CE",
    city: "Karachi",
    website: "https://creditbook.pk",
    logo_url: "https://logo.clearbit.com/creditbook.pk",
    founder_name: "Hisham Adamjee",
    founder_role: "Co-founder & CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/men/14.jpg",
    current_revenue: 55_000_000,
    investment_raised: 11_000_000,
    number_of_customers: 4_500_000,
    total_employees: 210,
    pasha_verified: true,
  },
  {
    id: "00000008-0000-0000-0000-000000000008",
    startup_name: "Tez Financial",
    tagline: "Instant digital loans for micro-entrepreneurs",
    primary_industry: "FinTech",
    nic_name: null,
    city: "Lahore",
    website: "https://tezfinancial.pk",
    logo_url: "https://logo.clearbit.com/tez.com",
    founder_name: "Naureen Hyat",
    founder_role: "Co-founder",
    founder_photo_url: "https://randomuser.me/api/portraits/women/55.jpg",
    current_revenue: 62_000_000,
    investment_raised: 18_000_000,
    number_of_customers: 150000,
    total_employees: 175,
    pasha_verified: false,
  },
  {
    id: "00000009-0000-0000-0000-000000000009",
    startup_name: "Farmdar",
    tagline: "Satellite & AI crop monitoring for Pakistani farmers",
    primary_industry: "AgriTech",
    nic_name: "NUST NIC",
    city: "Islamabad",
    website: "https://farmdar.com",
    logo_url: "https://logo.clearbit.com/farmdar.com",
    founder_name: "Talha Khan",
    founder_role: "Founder & CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/men/77.jpg",
    current_revenue: 7_000_000,
    investment_raised: 3_200_000,
    number_of_customers: 8000,
    total_employees: 42,
    pasha_verified: false,
  },
  {
    id: "0000000a-0000-0000-0000-00000000000a",
    startup_name: "OneLoad",
    tagline: "Largest digital payments & branchless banking network",
    primary_industry: "FinTech",
    nic_name: null,
    city: "Karachi",
    website: "https://oneload.pk",
    logo_url: "https://logo.clearbit.com/oneload.pk",
    founder_name: "Muhammad Yar",
    founder_role: "Founder & CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/men/41.jpg",
    current_revenue: 400_000_000,
    investment_raised: 25_000_000,
    number_of_customers: 1_200_000,
    total_employees: 380,
    pasha_verified: true,
  },
  {
    id: "0000000b-0000-0000-0000-00000000000b",
    startup_name: "Educative.io PK",
    tagline: "Interactive coding courses built for Pakistani developers",
    primary_industry: "EdTech",
    nic_name: "Plan9",
    city: "Lahore",
    website: "https://educative.io",
    logo_url: "https://logo.clearbit.com/educative.io",
    founder_name: "Fahim Ul Haq",
    founder_role: "Co-founder & CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/men/63.jpg",
    current_revenue: 35_000_000,
    investment_raised: 8_000_000,
    number_of_customers: 75000,
    total_employees: 110,
    pasha_verified: false,
  },
  {
    id: "0000000c-0000-0000-0000-00000000000c",
    startup_name: "Markaz",
    tagline: "Social commerce — sell anything without a shop",
    primary_industry: "E-Commerce",
    nic_name: "NIC Lahore",
    city: "Lahore",
    website: "https://markaz.app",
    logo_url: "https://logo.clearbit.com/markaz.app",
    founder_name: "Rohan Khurram",
    founder_role: "Co-founder & CEO",
    founder_photo_url: "https://randomuser.me/api/portraits/men/29.jpg",
    current_revenue: 22_000_000,
    investment_raised: 9_000_000,
    number_of_customers: 500000,
    total_employees: 85,
    pasha_verified: false,
  },
] as const;
